### ISSUE TITLE
Make the input format more generic

### ISSUE THREAD

**Issue by gaieges** [overipio/splunkuf-ansible#4]
@adamstrawson had a great suggestion, saving it here so we don't lose it.

Right now the inputs are pretty specific to file monitors, however in order to make this more generic and accessible, we want to modify the input format to something like this:

```yaml
- splunkforwarder_inputs_input:
   - type: monitor
     type_value: "/hello/world.log"
     settings:          
       sourcetype: app_log
       index: differentindex
   - type: splunktcp
     settings:
       enableS2SHeartbeat: true
       inputShutdownTimeout: 5
```

- `type` is the input type (eg. monitor, batch, tcp, etc)
- `type_value` is optional, if the type is `monitor`, then it'll be a log file, if it's `tcp`, then the IP:PORT for example
- `settings` is a key:value list of input Additional Settings

Which would then translate to;

```
[monitor:///hello/world.log]
index = differentindex
sourcetype = app_log

[splunktcp]
enableS2SHeartbeat = true
inputShutdownTimeout = 5
```

And would create a number of input blocks managed by ansible.

Additionally, it would be good to have a `{{splunkforwarder_inputs_extra}}` argument to paste in any other arguments there that wouldn't be covered by the more simplistic approach above.
